# Generated by Django 5.1 on 2024-08-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("manager", "manager"), ("customer", "customer")],
                max_length=50,
                verbose_name="role",
            ),
        ),
    ]
